image: registry.gitlab.com/thecodeine/environment:docker-compose

stages:
  - prepare
  - build
  - test
  - release
  - review
  - deploy
  - cleanup

variables:
  DOCKER_DRIVER: overlay
  BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_COMPOSE_ARGS: "-f docker-compose.yml -f docker-compose.build.yml"
  GIT_STRATEGY: none

before_script:
  - &docker-login
    docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE

.git-lfs: &git-lfs
  before_script:
    - git lfs pull

.tags: &tags
  tags:
    - docker

prepare:
  <<: *git-lfs
  <<: *tags
  image: registry.gitlab.com/thecodeine-docker/php:php-fpm-node-ruby
  variables:
    GIT_STRATEGY: clone
  stage: prepare
  script:
    - make prepare
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - bin/
      - vendor/
  artifacts:
    paths:
      - bin/
      - vendor/
    expire_in: 1 day
  only:
    - branches

docker-compose:
  <<: *tags
  image: alpine
  stage: prepare
  variables:
    GIT_STRATEGY: clone
  before_script: []
  script:
    - echo "Prepare docker-compose files"
  artifacts:
    paths:
      - docker-compose.build.yml
      - docker-compose.yml
      - docker-test.sh
    expire_in: 9 day
  only:
    - branches

.build-and-push: &build-and-push
  script:
    - *docker-login
    - export DOCKER_COMPOSE_ARGS=${DOCKER_COMPOSE_ARGS:-$DOCKER_ENV_DOCKER_COMPOSE_ARGS}
    - docker-compose $DOCKER_COMPOSE_ARGS build --pull
    - docker-compose $DOCKER_COMPOSE_ARGS push

.dependencies-prepare: &dependencies-prepare
  dependencies:
    - prepare

.dependencies-docker-compose: &dependencies-docker-compose
  dependencies:
    - docker-compose

build-package:
  image: registry.gitlab.com/thecodeine-docker/php:7.0-fpm
  stage: build
  variables:
    GIT_STRATEGY: clone
  before_script:
    - make prepare
  script:
    - php build/package_release.php
    - mkdir packages
    - mv build/packages/*update.zip packages/
    - for file in packages/*update.zip; do mv -v "$file" "${file/-update/}"; done;
  only:
    - tags
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - bin/
      - vendor/
  artifacts:
    paths:
      - packages/*
    expire_in: 3 mos

build-test:
  <<: *build-and-push
  <<: *dependencies-prepare
  <<: *tags
  stage: build
  variables:
    BUILD_TASK: $CI_JOB_NAME
    SYMFONY_ENV: test
    GIT_STRATEGY: clone
  before_script:
    - export IMAGE="${BUILD_IMAGE:-$DOCKER_ENV_BUILD_IMAGE}-test"
  only:
    - branches

.dependencies-test: &dependencies-test
  before_script:
    - *docker-login
    - export TEST_IMAGE="${BUILD_IMAGE:-$DOCKER_ENV_BUILD_IMAGE}-test"
    - docker pull $TEST_IMAGE

.test: &test
  <<: *dependencies-test
  <<: *dependencies-docker-compose
  <<: *tags
  stage: test
  script:
    - export IMAGE=$TEST_IMAGE
    - export MAKE_TASK=$CI_JOB_NAME
    - ./docker-test.sh $ARGS
  only:
    - branches

test:
  <<: *test
  variables:
    ARGS: --no-deps app

.release: &release
  <<: *build-and-push
  <<: *git-lfs
  <<: *dependencies-prepare
  <<: *tags
  stage: release

release-branch:
  <<: *release
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    GIT_STRATEGY: clone
  only:
    - branches
  except:
    - v2.6.1

release-master:
  <<: *release
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:latest
    GIT_STRATEGY: clone
  only:
    - v2.6.1

.deploy: &deploy
  <<: *dependencies-docker-compose
  <<: *tags
  image: registry.gitlab.com/thecodeine/environment:docker-machine
  script:
    - export DOCKER_COMPOSE_ARGS=${DOCKER_COMPOSE_ARGS:-$DOCKER_ENV_DOCKER_COMPOSE_ARGS}
    - docker-compose $DOCKER_COMPOSE_ARGS pull
    - docker-compose $DOCKER_COMPOSE_ARGS -p $PROJECT down -v
    - docker-compose $DOCKER_COMPOSE_ARGS -p $PROJECT up -d

review:
  <<: *deploy
  stage: review
  variables:
    VIRTUAL_HOST: $CI_COMMIT_REF_NAME-$CI_PROJECT_NAME.$HOST
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PROJECT: review_$CI_COMMIT_REF_NAME-$CI_PROJECT_NAME
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_NAME-$CI_PROJECT_NAME.$HOST
    on_stop: stop-review
  only:
    - branches
  except:
    - v2.6.1

deploy-master:
  <<: *deploy
  stage: deploy
  variables:
    VIRTUAL_HOST: $CI_PROJECT_NAME.$HOST
    IMAGE: $CI_REGISTRY_IMAGE:latest
    PROJECT: staging_$CI_PROJECT_NAME
  environment:
    name: staging
    url: http://$CI_PROJECT_NAME.$HOST
  only:
    - v2.6.1

stop-review:
  <<: *deploy
  stage: cleanup
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PROJECT: review_$CI_COMMIT_REF_NAME-$CI_PROJECT_NAME
  script:
    - docker-compose ${DOCKER_COMPOSE_ARGS:-$DOCKER_ENV_DOCKER_COMPOSE_ARGS} -p $PROJECT down -v
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - v2.6.1
