language: php

php:
  # At the moment Composer can't resolve dependencies for these PHP versions.
  #- 5.3
  #- 5.4
  #- 5.5
  - 5.6
  - 7.0

before_script:
  - composer install
  - cd app

script:
  - phpunit
  - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS
  - bin/php-cs-fixer fix  -v --dry-run "${COMMIT_SCA_FILES[@]}"
