language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:

  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

install:
  - composer install

script:
  - composer test
  - bin/php-cs-fixer fix -v --dry-run --diff
