language: php

php:
  # At the moment Composer can't resolve dependencies for these PHP versions.
  #- 5.3
  #- 5.4
  #- 5.5
  - 5.6
  - 7.0

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

install:
  - composer install

script:
  - bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist app/bundles
  - bin/php-cs-fixer fix -v --dry-run --diff
