dist: trusty
language: php

services:
  - mysql

notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Create mautictest database
  - mysql --version
  - mysql -e 'DROP DATABASE IF EXISTS mautictest;'
  - mysql -e 'CREATE DATABASE mautictest;'

  # increase memory limit for all PHP processes
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

  # set to test environment for Symfony's commands in post install commands
  - export SYMFONY_ENV="test"

install:
  - composer install

  # Clobber is needed because PCOV normally only works with PHPUnit 8+. Needed only to run test coverage.
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]; then pecl install pcov && composer require --dev pcov/clobber && bin/pcov clobber; fi

script:
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]; 
    then composer test -- --coverage-clover=coverage.xml && bash <(curl -s https://codecov.io/bash); 
    else composer test; fi

jobs:
  include:
    - stage: test
      php: 7.2
      env: DB=mariadb
      addons:
        mariadb: '10.2'
    - 
      php: 7.3
      env: DB=mariadb
      addons:
        mariadb: '10.2'
    - 
      name: PHPSTAN
      script: composer phpstan
    -
      name: Rector
      script: composer rector -- --dry-run --no-progress-bar
    -
      name: CS Fixer
      script: bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --show-progress=dots --diff $(git diff -- '*.php' --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")
