language: php

php:
  # At the moment Composer can't resolve dependencies for these PHP versions.
  #- 5.3
  #- 5.4
  #- 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then composer global require phpstan/phpstan-shim; fi
  - composer install

script:
  - composer run-script test
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then ~/.composer/vendor/phpstan/phpstan-shim/phpstan.phar analyse app/bundles/CampaignBundle/Model; fi
