language: php

php:
  # At the moment Composer can't resolve dependencies for these PHP versions.
  #- 5.3
  #- 5.4
  #- 5.5
  - 5.6.19
  - 7.0
  - 7.1

before_script:
  - composer install

script:
  - composer run-script test
