dist: precise

language: php

services:
  - mysql

php:
  - 5.6.19
  - 7.0
  - 7.1

before_install:
  # Create mautictest database
  - mysql -e 'CREATE DATABASE mautictest;'

  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

  # install PHPSTAN for PHP 7+
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then composer global require phpstan/phpstan-shim; fi

install:
  - composer install

script:

  # Run PHPUnit
  - bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist

  # Run PHPSTAN analysis for PHP 7+
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then ~/.composer/vendor/phpstan/phpstan-shim/phpstan.phar analyse app/bundles/CampaignBundle app/bundles/WebhookBundle app/bundles/LeadBundle; fi

  # Check if the code standards weren't broken.
  # Run it only on PHP 7.1 which should be the fastest. No need to run it for all PHP versions
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then bin/php-cs-fixer fix -v --dry-run --diff; fi
