dist: trusty
language: php

services:
  - mysql

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Create mautictest database
  - mysql -e 'CREATE DATABASE mautictest;'

  # increase memory limit for all PHP processes
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

  # set to test environment for Symfony's commands in post install commands
  - export SYMFONY_ENV="test"

install:
  - composer install

script:

  # Run PHPUnit
  - composer test

  # Run PHPSTAN analysis
  - composer phpstan

  # Check if the code standards weren't broken.
  - composer cs
