# TravisCI configuration for mautic/mautic

language: php
os:
  - linux
dist: bionic

services:
  - mysql

cache:
  directories:
    - "${HOME}/.composer/cache"

env:
  global:
    # Set to test environment for Symfony's commands in post install commands
    - SYMFONY_ENV="test"

jobs:
  include:
    - stage: test
      name: "PHP 7.2"
      php: 7.2
    -
      name: "PHP 7.4"
      php: 7.4
    -
      name: "MariaDB, PHP 7.2"
      php: 7.2
      env: DB="mariadb"
      addons:
        mariadb: 10.2
    -
      name: "MariaDB, PHP 7.3"
      php: 7.3
      env: DB="mariadb"
      addons:
        mariadb: 10.2
    -
      name: "MariaDB, PHP 7.4"
      php: 7.4
      env: DB="mariadb"
      addons:
        mariadb: 10.2
    -
      name: "PHPStan"
      script: composer phpstan
    -
      name: "Rector"
      script: composer rector -- --dry-run --no-progress-bar
    -
      name: "CS Fixer"
      script: |
        bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --show-progress=dots \
          --diff $(git diff -- '*.php' --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")
    - stage: coverage
      name: "Coverage on PHP 7.3"
      php: 7.3
      install:
        - composer install --no-suggest
        # Clobber is needed because PCOV normally only works with PHPUnit 8+. Needed only to run test coverage.
        - pecl install pcov
        - composer require --dev pcov/clobber
        - bin/pcov clobber
      script:
        - composer test -- --coverage-clover=coverage.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)

before_install:
  # Create mautictest database
  - mysql --version
  - mysql -e 'DROP DATABASE IF EXISTS mautictest;'
  - mysql -e 'CREATE DATABASE mautictest;'
  - mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost;'

  # Increase memory limit for all PHP processes
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Turn off XDebug extension
  - phpenv config-rm xdebug.ini || true

  # Temp downgrade Composer to v1 (see https://github.com/mautic/mautic/pull/9315 for details)
  - composer self-update --1

  # Install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

install:
  - travis_retry composer install --no-suggest

script:
  - composer test

notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never
