language: php

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE mautictest;'

env:
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_USER: travis
  DB_PASSWD: ''
  DB_NAME: mautictest

php:
  # At the moment Composer can't resolve dependencies for these PHP versions.
  #- 5.3
  #- 5.4
  #- 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install

script:
  - composer run-script test
