version: '2.1'
services:
  apache:
    image: webdevops/apache:alpine-3
    environment:
      - WEB_PHP_SOCKET=app:9000
      - PHP_SOCKET=app:9000
      - WEB_DOCUMENT_ROOT=/usr/src/app
    volumes_from:
      - app
    restart: on-failure:3

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    healthcheck:
      test:
        - "CMD-SHELL"
        - "
        export MYSQL_PWD=$${MYSQL_PASSWORD:-$$MYSQL_ROOT_PASSWORD}; \
        host=$$(hostname --ip-address || echo '127.0.0.1'); \
        user=$${MYSQL_USER:-root}; \
        select=$$(echo 'SELECT 1' | mysql -u\"$$user\" -h\"$$host\" --silent); \
        if [ \"$$select\" = '1' ]; then exit 0; else exit 1; fi
        "
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    restart: on-failure:3

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      MAKE_TASK: ${MAKE_TASK}
      SYMFONY_ENV: ${SYMFONY_ENV:-prod}
      MAUTIC_DB_HOST: db
      MAUTIC_DB_NAME: app
      MAUTIC_DB_USER: root
      MAUTIC_DB_PASSWORD: password
      MAUTIC_TRUSTED_PROXIE: "0.0.0.0/0"
    restart: on-failure:3

volumes:
  db-data:
